package carsharing;

/**
 * Represents a customer in the car sharing system.
 */
public class Customer {
    private final int id;
    private final String name;
    private Integer rentedCarId;

    public Customer(int id, String name, Integer rentedCarId) {
        this.id = id;
        this.name = name;
        this.rentedCarId = rentedCarId;
    }

    public Customer(String name) {
        this.id = -1; // ID will be auto-generated by the database
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Integer getRentedCarId() {
        return rentedCarId;
    }

    public void setRentedCarId(Integer rentedCarId) {
        this.rentedCarId = rentedCarId;
    }

    @Override
    public String toString() {
        return "Customer [id=" + id + ", name=" + name + ", rentedCarId=" + rentedCarId + "]";
    }
}
